In [ ]:
name_file_ar = 'content/lastfm_artist_list.csv'
name_file_us = 'content/lastfm_user_scrobbles.csv'

In [ ]:
import pandas as pd

In [ ]:
data_1 = pd.read_csv(name_file_ar)

In [ ]:
data_1

       artist_id   artist_name
0              1       __Max__
1              2       _Algol_
2              3     -123 Min.
3              4          -Oz-
4              5  -T De Sangre
...          ...           ...
17488      17489          鷺巣詩郎
17489      17490           黃立行
17490      17491           黄义达
17491      17492         黒木メイサ
17492      17493            鼓童

[17493 rows x 2 columns]

In [ ]:
data_2 = pd.read_csv(name_file_us)

In [ ]:
data_2

       user_id  artist_id  scrobbles
0            1       4562      13883
1            1      10191      11690
2            1        494      11351
3            1       6673      10300
4            1       8402       8983
...        ...        ...        ...
92787     1892      10098        278
92788     1892       8660        263
92789     1892       3274        258
92790     1892       4240        232
92791     1892      10842        228

[92792 rows x 3 columns]

In [ ]:
data = pd.merge(data_2, data_1, on='artist_id')

In [ ]:
data

       user_id  artist_id  scrobbles          artist_name
0            1       4562      13883          Duran Duran
1            3       4562        228          Duran Duran
2           25       4562         85          Duran Duran
3           26       4562         10          Duran Duran
4           60       4562        528          Duran Duran
...        ...        ...        ...                  ...
92787     1892      10879        337            Nyktalgia
92788     1892       1357        297      Atsakau Niekada
92789     1892       4360        281   Domantas Razauskas
92790     1892       1330        280              Atalyja
92791     1892       8660        263  Les Chants De Nihil

[92792 rows x 4 columns]

In [ ]:
data = data.drop(['artist_id'], axis='columns')

In [ ]:
data

       user_id  scrobbles          artist_name
0            1      13883          Duran Duran
1            3        228          Duran Duran
2           25         85          Duran Duran
3           26         10          Duran Duran
4           60        528          Duran Duran
...        ...        ...                  ...
92787     1892        337            Nyktalgia
92788     1892        297      Atsakau Niekada
92789     1892        281   Domantas Razauskas
92790     1892        280              Atalyja
92791     1892        263  Les Chants De Nihil

[92792 rows x 3 columns]

In [ ]:
import numpy as np
import sklearn
from sklearn.decomposition import TruncatedSVD

In [ ]:
recommend_data = data.pivot_table(values='scrobbles', index='user_id', columns='artist_name', fill_value=0)

In [ ]:
X = recommend_data.T

In [ ]:
SVD = TruncatedSVD(n_components=12, random_state=5)
resultant_matrix = SVD.fit_transform(X)
resultant_matrix.shape

(17492, 12)

In [ ]:
corr_mat = np.corrcoef(resultant_matrix)
corr_mat.shape

(17492, 17492)

In [ ]:
col_idx = recommend_data.columns.get_loc("Nyktalgia")
corr_specific = corr_mat[col_idx]
pd.DataFrame({'corr_specific':corr_specific, 'Artist': recommend_data.columns})\
.sort_values('corr_specific', ascending=False)\
.head(10)

       corr_specific               Artist
10165       1.000000            Mortifera
8622        1.000000  Les Chants De Nihil
10838       1.000000            Nyktalgia
11376       1.000000          Peste Noire
1338        1.000000      Atsakau Niekada
4337        1.000000   Domantas Razauskas
16120       1.000000             Vilkduja
1311        1.000000              Atalyja
12972       0.999971     Shape Of Despair
1165        0.999949             Argharus